export type BadgeCategory =
  | "ACHIEVEMENT"
  | "MILESTONE"
  | "COMMUNITY"
  | "SPECIAL"
  | "VERIFICATION"
  | "BRAND";
export type BadgeRarity = "COMMON" | "RARE" | "EPIC" | "LEGENDARY";

export interface BadgeDefinition {
  id: string; // constant ID for code references
  name: string;
  description: string;
  icon: string; // Emoji or URL
  category: BadgeCategory;
  rarity: BadgeRarity;
  xpReward: number;
  criteria?: any; // For documentation
}

export const BADGES: BadgeDefinition[] = [
  // ========================= VERIFICATION & ONBOARDING (5) =========================
  {
    id: "verified_identity",
    name: "Identity Verified",
    description: "Completed identity verification",
    icon: "🆔",
    category: "VERIFICATION",
    rarity: "COMMON",
    xpReward: 100,
  },
  {
    id: "verified_pro",
    name: "Pro Influencer",
    description: "Reached 10k followers with high engagement",
    icon: "🌟",
    category: "VERIFICATION",
    rarity: "RARE",
    xpReward: 500,
  },
  {
    id: "profile_complete",
    name: "Profile Perfectionist",
    description: "Completed 100% of profile details",
    icon: "📝",
    category: "VERIFICATION",
    rarity: "COMMON",
    xpReward: 50,
  },
  {
    id: "first_login",
    name: "Welcome Aboard",
    description: "Logged in for the first time",
    icon: "👋",
    category: "VERIFICATION",
    rarity: "COMMON",
    xpReward: 10,
  },
  {
    id: "social_connected",
    name: "Social Butterfly",
    description: "Connected both Instagram and YouTube",
    icon: "🔗",
    category: "VERIFICATION",
    rarity: "COMMON",
    xpReward: 50,
  },

  // ========================= DEAL MILESTONES (10) =========================
  {
    id: "first_deal",
    name: "First Steps",
    description: "Completed your first deal",
    icon: "💰",
    category: "MILESTONE",
    rarity: "COMMON",
    xpReward: 100,
  },
  {
    id: "five_deals",
    name: "High Five",
    description: "Completed 5 deals",
    icon: "✋",
    category: "MILESTONE",
    rarity: "COMMON",
    xpReward: 200,
  },
  {
    id: "ten_deals",
    name: "On Fire",
    description: "Completed 10 deals",
    icon: "🔥",
    category: "MILESTONE",
    rarity: "RARE",
    xpReward: 300,
  },
  {
    id: "twenty_five_deals",
    name: "Lightning Speed",
    description: "Completed 25 deals",
    icon: "⚡",
    category: "MILESTONE",
    rarity: "RARE",
    xpReward: 500,
  },
  {
    id: "fifty_deals",
    name: "Professional",
    description: "Completed 50 deals",
    icon: "🥇",
    category: "MILESTONE",
    rarity: "EPIC",
    xpReward: 1000,
  },
  {
    id: "hundred_deals",
    name: "Centurion",
    description: "Completed 100 deals",
    icon: "💯",
    category: "MILESTONE",
    rarity: "EPIC",
    xpReward: 2000,
  },
  {
    id: "five_hundred_deals",
    name: "Hall of Fame",
    description: "Completed 500 deals",
    icon: "🏛️",
    category: "MILESTONE",
    rarity: "LEGENDARY",
    xpReward: 5000,
  },
  {
    id: "thousand_deals",
    name: "Unicorn",
    description: "Completed 1000 deals — truly legendary",
    icon: "🦄",
    category: "MILESTONE",
    rarity: "LEGENDARY",
    xpReward: 10000,
  },
  {
    id: "deal_streak_5",
    name: "On a Roll",
    description: "Completed 5 deals in a month",
    icon: "🎳",
    category: "MILESTONE",
    rarity: "RARE",
    xpReward: 150,
  },
  {
    id: "deal_streak_10",
    name: "Unstoppable",
    description: "Completed 10 deals in a month",
    icon: "🔥",
    category: "MILESTONE",
    rarity: "EPIC",
    xpReward: 300,
  },

  // ========================= EARNINGS (8) =========================
  {
    id: "earn_1k",
    name: "First Earner",
    description: "Earned total ₹1,000",
    icon: "💵",
    category: "ACHIEVEMENT",
    rarity: "COMMON",
    xpReward: 50,
  },
  {
    id: "earn_10k",
    name: "Side Hustle",
    description: "Earned total ₹10,000",
    icon: "💴",
    category: "ACHIEVEMENT",
    rarity: "COMMON",
    xpReward: 150,
  },
  {
    id: "earn_50k",
    name: "Serious Money",
    description: "Earned total ₹50,000",
    icon: "💶",
    category: "ACHIEVEMENT",
    rarity: "RARE",
    xpReward: 300,
  },
  {
    id: "earn_1lakh",
    name: "The 1 Lakh Club",
    description: "Earned total ₹1,00,000",
    icon: "💷",
    category: "ACHIEVEMENT",
    rarity: "EPIC",
    xpReward: 500,
  },
  {
    id: "earn_5lakh",
    name: "High Roller",
    description: "Earned total ₹5,00,000",
    icon: "🏦",
    category: "ACHIEVEMENT",
    rarity: "EPIC",
    xpReward: 1000,
  },
  {
    id: "earn_10lakh",
    name: "Millionaire",
    description: "Earned total ₹10,00,000",
    icon: "💎",
    category: "ACHIEVEMENT",
    rarity: "LEGENDARY",
    xpReward: 2000,
  },
  {
    id: "earn_1crore",
    name: "Crorepati",
    description: "Earned total ₹1,00,00,000",
    icon: "🏰",
    category: "ACHIEVEMENT",
    rarity: "LEGENDARY",
    xpReward: 10000,
  },
  {
    id: "fast_earner",
    name: "Money Magnet",
    description: "Earned ₹50,000 in a single month",
    icon: "🧲",
    category: "ACHIEVEMENT",
    rarity: "EPIC",
    xpReward: 500,
  },

  // ========================= PERFORMANCE & QUALITY (12) =========================
  {
    id: "first_5_star",
    name: "Five Star",
    description: "Received a 5-star review",
    icon: "⭐",
    category: "ACHIEVEMENT",
    rarity: "COMMON",
    xpReward: 50,
  },
  {
    id: "five_5_star",
    name: "Consistent Quality",
    description: "Received 5 five-star reviews",
    icon: "⭐",
    category: "ACHIEVEMENT",
    rarity: "RARE",
    xpReward: 150,
  },
  {
    id: "ten_5_star",
    name: "Quality Guru",
    description: "Received 10 five-star reviews",
    icon: "🏆",
    category: "ACHIEVEMENT",
    rarity: "EPIC",
    xpReward: 300,
  },
  {
    id: "perfect_rating",
    name: "Perfectionist",
    description: "Maintained 5.0 rating after 10 deals",
    icon: "🎯",
    category: "ACHIEVEMENT",
    rarity: "LEGENDARY",
    xpReward: 500,
  },
  {
    id: "speed_demon",
    name: "Lightning Speed",
    description: "Submitted content within 24 hours",
    icon: "⚡",
    category: "ACHIEVEMENT",
    rarity: "RARE",
    xpReward: 100,
  },
  {
    id: "early_bird",
    name: "Early Bird",
    description: "Submitted before deadline 5 times",
    icon: "🌅",
    category: "ACHIEVEMENT",
    rarity: "RARE",
    xpReward: 200,
  },
  {
    id: "no_revisions",
    name: "Nailed It",
    description: "Content approved with zero revisions",
    icon: "🔨",
    category: "ACHIEVEMENT",
    rarity: "RARE",
    xpReward: 100,
  },
  {
    id: "creative_genius",
    name: "Creative Genius",
    description: "Brand praised creativity in review",
    icon: "🎨",
    category: "ACHIEVEMENT",
    rarity: "EPIC",
    xpReward: 150,
  },
  {
    id: "viral_post",
    name: "Going Viral",
    description: "Post achieved 10x average engagement",
    icon: "📈",
    category: "ACHIEVEMENT",
    rarity: "LEGENDARY",
    xpReward: 500,
  },
  {
    id: "highly_responsive",
    name: "Chatty",
    description: "Reply time under 30 mins for 10 messages",
    icon: "💬",
    category: "ACHIEVEMENT",
    rarity: "COMMON",
    xpReward: 100,
  },
  {
    id: "category_king",
    name: "Category King",
    description: "Top performer in your primary niche",
    icon: "👑",
    category: "ACHIEVEMENT",
    rarity: "LEGENDARY",
    xpReward: 1000,
  },
  {
    id: "city_champion",
    name: "City Champion",
    description: "Most completed deals in your city",
    icon: "🏙️",
    category: "ACHIEVEMENT",
    rarity: "EPIC",
    xpReward: 750,
  },

  // ========================= REFERRALS & COMMUNITY (8) =========================
  {
    id: "first_referral",
    name: "Friend Bringer",
    description: "Referred 1 user who completed a deal",
    icon: "🗣️",
    category: "COMMUNITY",
    rarity: "COMMON",
    xpReward: 200,
  },
  {
    id: "five_referrals",
    name: "Influencer of Influencers",
    description: "Referred 5 active users",
    icon: "📢",
    category: "COMMUNITY",
    rarity: "RARE",
    xpReward: 500,
  },
  {
    id: "ten_referrals",
    name: "Community Leader",
    description: "Referred 10 active users",
    icon: "🏘️",
    category: "COMMUNITY",
    rarity: "EPIC",
    xpReward: 1000,
  },
  {
    id: "referral_king",
    name: "Empire Builder",
    description: "Referred 50 active users",
    icon: "🏰",
    category: "COMMUNITY",
    rarity: "LEGENDARY",
    xpReward: 5000,
  },
  {
    id: "community_helper",
    name: "Helping Hand",
    description: "Resolved a dispute amicably",
    icon: "🤝",
    category: "COMMUNITY",
    rarity: "RARE",
    xpReward: 150,
  },
  {
    id: "bug_reporter",
    name: "Bug Hunter",
    description: "Reported a verified bug",
    icon: "🐛",
    category: "COMMUNITY",
    rarity: "RARE",
    xpReward: 200,
  },
  {
    id: "feedback_giver",
    name: "Idea Generator",
    description: "Provided implemented feedback",
    icon: "💡",
    category: "COMMUNITY",
    rarity: "RARE",
    xpReward: 200,
  },
  {
    id: "beta_tester",
    name: "Pioneer",
    description: "Participated in platform beta",
    icon: "🔭",
    category: "COMMUNITY",
    rarity: "EPIC",
    xpReward: 500,
  },

  // ========================= SPECIAL & HIDDEN (12) =========================
  {
    id: "night_owl",
    name: "Night Owl",
    description: "Submitted work between 2 AM and 5 AM",
    icon: "🦉",
    category: "SPECIAL",
    rarity: "RARE",
    xpReward: 100,
  },
  {
    id: "weekend_warrior",
    name: "Weekend Warrior",
    description: "Completed a deal on a Sunday",
    icon: "⚔️",
    category: "SPECIAL",
    rarity: "COMMON",
    xpReward: 100,
  },
  {
    id: "diverse_portfolio",
    name: "Versatile",
    description: "Completed deals in 5 different categories",
    icon: "🤹",
    category: "SPECIAL",
    rarity: "EPIC",
    xpReward: 300,
  },
  {
    id: "loyalist",
    name: "Brand Favorite",
    description: "Worked with the same brand 5 times",
    icon: "💍",
    category: "SPECIAL",
    rarity: "EPIC",
    xpReward: 300,
  },
  {
    id: "comeback_kid",
    name: "Comeback Kid",
    description: "Returned after 3 months inactivity",
    icon: "🔄",
    category: "SPECIAL",
    rarity: "RARE",
    xpReward: 100,
  },
  {
    id: "trendsetter",
    name: "Trendsetter",
    description: "First to use a new feature",
    icon: "✨",
    category: "SPECIAL",
    rarity: "EPIC",
    xpReward: 200,
  },
  {
    id: "holiday_special",
    name: "Festive Spirit",
    description: "Completed a deal during Diwali",
    icon: "🪔",
    category: "SPECIAL",
    rarity: "RARE",
    xpReward: 200,
  },
  {
    id: "mystery_badge",
    name: "???",
    description: "A mystery achievement",
    icon: "❓",
    category: "SPECIAL",
    rarity: "LEGENDARY",
    xpReward: 1000,
  },
  {
    id: "og_member",
    name: "OG Member",
    description: "Joined within the first month of launch",
    icon: "🎖️",
    category: "SPECIAL",
    rarity: "LEGENDARY",
    xpReward: 500,
  },
  {
    id: "platform_veteran",
    name: "Veteran",
    description: "Active on platform for 1 year",
    icon: "🎂",
    category: "SPECIAL",
    rarity: "EPIC",
    xpReward: 500,
  },
  {
    id: "hot_creator",
    name: "Hot Creator",
    description: "Topped the weekly leaderboard",
    icon: "🔥",
    category: "SPECIAL",
    rarity: "EPIC",
    xpReward: 300,
  },
  {
    id: "challenge_champion",
    name: "Challenge Champion",
    description: "Completed 10 weekly challenges",
    icon: "🏅",
    category: "SPECIAL",
    rarity: "LEGENDARY",
    xpReward: 1000,
  },

  // ========================= BRAND BADGES (10) =========================
  {
    id: "first_campaign",
    name: "Campaign Launcher",
    description: "Created your first campaign",
    icon: "✨",
    category: "BRAND",
    rarity: "COMMON",
    xpReward: 100,
  },
  {
    id: "campaign_master",
    name: "Campaign Master",
    description: "Completed 25 campaigns",
    icon: "🎓",
    category: "BRAND",
    rarity: "EPIC",
    xpReward: 1000,
  },
  {
    id: "fast_approver",
    name: "Fast Approver",
    description: "Approved content within 6 hours 10 times",
    icon: "⚡",
    category: "BRAND",
    rarity: "RARE",
    xpReward: 200,
  },
  {
    id: "creator_favorite",
    name: "Creator Favorite",
    description: "Received 10 five-star reviews from influencers",
    icon: "❤️",
    category: "BRAND",
    rarity: "EPIC",
    xpReward: 500,
  },
  {
    id: "roi_master",
    name: "ROI Master",
    description: "Achieved 5x return on campaign investment",
    icon: "📊",
    category: "BRAND",
    rarity: "LEGENDARY",
    xpReward: 1000,
  },
  {
    id: "partnership_pro",
    name: "Partnership Pro",
    description: "Maintained 5+ repeat influencer relationships",
    icon: "🤝",
    category: "BRAND",
    rarity: "EPIC",
    xpReward: 500,
  },
  {
    id: "big_spender",
    name: "Whale",
    description: "Spent ₹1 Lakh on a single campaign",
    icon: "🐳",
    category: "BRAND",
    rarity: "EPIC",
    xpReward: 500,
  },
  {
    id: "mega_campaign",
    name: "Mega Campaign",
    description: "Ran a campaign with 50+ influencers",
    icon: "🌍",
    category: "BRAND",
    rarity: "LEGENDARY",
    xpReward: 2000,
  },
  {
    id: "fair_payer",
    name: "Fair Payer",
    description: "Always paid above market average",
    icon: "💳",
    category: "BRAND",
    rarity: "RARE",
    xpReward: 300,
  },
  {
    id: "brand_ambassador",
    name: "Brand Ambassador",
    description: "Active on the platform for 6 months",
    icon: "🏢",
    category: "BRAND",
    rarity: "RARE",
    xpReward: 250,
  },
];

// Rarity colors for UI
export const RARITY_COLORS: Record<
  BadgeRarity,
  { bg: string; text: string; border: string; glow: string }
> = {
  COMMON: {
    bg: "rgba(156, 163, 175, 0.15)",
    text: "#9ca3af",
    border: "#6b7280",
    glow: "none",
  },
  RARE: {
    bg: "rgba(59, 130, 246, 0.15)",
    text: "#3b82f6",
    border: "#2563eb",
    glow: "0 0 8px rgba(59, 130, 246, 0.3)",
  },
  EPIC: {
    bg: "rgba(168, 85, 247, 0.15)",
    text: "#a855f7",
    border: "#9333ea",
    glow: "0 0 12px rgba(168, 85, 247, 0.4)",
  },
  LEGENDARY: {
    bg: "rgba(245, 158, 11, 0.15)",
    text: "#f59e0b",
    border: "#d97706",
    glow: "0 0 16px rgba(245, 158, 11, 0.5)",
  },
};

// Helper: Get badge by ID
export function getBadgeById(id: string): BadgeDefinition | undefined {
  return BADGES.find((b) => b.id === id);
}

// Helper: Get badges by category
export function getBadgesByCategory(
  category: BadgeCategory,
): BadgeDefinition[] {
  return BADGES.filter((b) => b.category === category);
}

// Helper: Get badges by rarity
export function getBadgesByRarity(rarity: BadgeRarity): BadgeDefinition[] {
  return BADGES.filter((b) => b.rarity === rarity);
}
